# Generated by Django 5.0.6 on 2024-09-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planepassenger',
            name='postbox_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
