# Generated by Django 5.0.6 on 2024-09-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation_app', '0003_alter_planepassenger_visa_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planepassenger',
            name='visa_document',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
