# Generated by Django 5.0.6 on 2024-09-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviation_app', '0004_alter_planepassenger_visa_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planepassenger',
            name='visa_document',
        ),
    ]
