# Generated by Django 5.0.6 on 2024-09-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation_app', '0005_remove_planepassenger_visa_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='planepassenger',
            name='visa_document',
            field=models.FileField(default=0, upload_to='visa_documents/'),
        ),
    ]
